### PR TITLE
Publishing and slight change in ReadMe

### PR DESCRIPTION
**Pull request by BentleySettin**
Same publishing updates that I made but now to the correct branch (cell-and-sd). 

Added the inclusion of the atlas temperature sensor in the readme but not extensive by any means.

### CODE REVIEW

**Comment by SUPScientist** [comment]
This PR has only one commit which is the simple readme update. Can you please add the other commits?

**Comment by BentleySettin** [comment]
@SUPScientist So I have been trying to figure out how to add commits to the current PR and I cannot find a way without closing the PR and then reopening a new one. Is this true or do you know another way to just add commits to current PR? 

Github continues to humble me :)

**Comment by SUPScientist** [comment]
Good question. I admit this is new to me also! It looks straightforward. Do the git add [your_changed_files] followed by git commit/commit message routine, then git push to the relevant branch (cell-and-sd). 
See other ways of describing it here: https://www.reddit.com/r/gitlab/comments/s1rko9/how_do_i_alter_or_add_commits_to_a_pending_merge/

**Comment by BentleySettin** [comment]
I amended my past commit of "publishing changes" to cell-sd branch... do you see it? I don't see it anywhere on my screen but not sure if it is different on yours.

**Comment by SUPScientist** [comment]
Afraid not. Just stopped in the lab to see if you were around and to see if we could troubleshoot but no dice. I'm going to merge this PR with the two words it changes to close it. Please open a new PR with the publishing changes.

**Pull request merged**
