### PR TITLE
publishing updates

### PR DESCRIPTION
**Pull request by BentleySettin**
updates to code to allow successful publishing of ec/rtd data.

### CODE REVIEW

**Review by SUPScientist — COMMENTED** [review]
As far as I can tell, this commit only removes two comments without changing functionality.

**Comment by BentleySettin** [comment]
Argh, apologies. Figuring this out before meeting. 

the argh is to myself, not you (obviously).

**Comment by BentleySettin** [comment]
did this work? :)

**Review by SUPScientist — COMMENTED** [review]
At first glance, this looks like it *un*does the desired changes... It does add a commit to the PR, so that's a step forward, but the commit itself appears to move things backwards.

**Review by SUPScientist — APPROVED** [review]

**Comment by SUPScientist** [comment]
OK, approved and merged. Is there anything else in a backlog of changes that needs to be added, or is this it? If this is everything, I will take a closer look for merging with the main branch. Thanks!

**Pull request merged**
